/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#bfb2da",
        "secondary-container": "#4d4465",
        "secondary-fixed": "#e9ddff",
        "surface-container-highest": "#36343a",
        "on-secondary-fixed-variant": "#4b4263",
        "on-secondary": "#342b4b",
        "on-background": "#e6e0e9",
        "tertiary-fixed": "#ffdf93",
        "outline": "#948e9c",
        "on-secondary-fixed": "#1f1635",
        "on-primary-fixed-variant": "#4f378a",
        "secondary-fixed-dim": "#cdc0e9",
        "surface": "#141218",
        "secondary": "#cdc0e9",
        "on-primary": "#381e72",
        "background": "#141218",
        "surface-container": "#211f24",
        "surface-container-lowest": "#0f0d13",
        "on-error": "#690005",
        "inverse-on-surface": "#322f35",
        "on-tertiary-fixed-variant": "#594400",
        "on-tertiary-container": "#503d00",
        "on-primary-container": "#e0d2ff",
        "on-tertiary-fixed": "#241a00",
        "on-tertiary": "#3e2e00",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#e9ddff",
        "tertiary-fixed-dim": "#e7c365",
        "error": "#ffb4ab",
        "tertiary": "#e7c365",
        "outline-variant": "#494551",
        "primary-fixed-dim": "#cfbcff",
        "surface-variant": "#36343a",
        "surface-dim": "#141218",
        "inverse-primary": "#6750a4",
        "inverse-surface": "#e6e0e9",
        "tertiary-container": "#c9a74d",
        "surface-bright": "#3b383e",
        "on-surface": "#e6e0e9",
        "surface-container-high": "#2b292f",
        "on-primary-fixed": "#22005d",
        "surface-container-low": "#1d1b20",
        "primary-container": "#6750a4",
        "on-surface-variant": "#cbc4d2",
        "primary": "#cfbcff",
        "surface-tint": "#cfbcff",
        "error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "md": "1rem",
        "safe-area": "3rem",
        "lg": "1.5rem",
        "sm": "0.5rem",
        "xs": "0.25rem",
        "xl": "2.5rem",
        "panel-gap": "2rem"
      },
      fontFamily: {
        "space": ["Space Grotesk", "sans-serif"],
        "manrope": ["Manrope", "sans-serif"],
        "h1": ["Space Grotesk", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "label-caps": ["Space Grotesk", "sans-serif"],
        "h3": ["Space Grotesk", "sans-serif"],
        "h2": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "h1": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "h3": ["24px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "h2": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
